"""FR-020 管理后台：合作模式多选，稿件回填作品数量。"""

from playwright.sync_api import expect


def _admin(page, demo_server):
    page.goto(f"{demo_server}/fr-yijian-daifa-iter3.html?tab=admin", wait_until="domcontentloaded")
    expect(page.locator("#view-admin")).to_be_visible()
    expect(page.locator("#pane-editors")).to_be_visible()


def _fill_required(page):
    page.locator("#edYb").fill("YB10999")
    page.locator("#edName").fill("试用")
    page.locator("#edNote").fill("客服接入")
    page.locator("#edPlatforms input[value='右豹']").check()


def test_admin_tabs_are_editors_and_works(page, demo_server):
    _admin(page, demo_server)
    bar = page.locator(".admin-tab-bar")
    expect(bar).to_contain_text("剪辑手管理")
    expect(bar).to_contain_text("稿件管理")
    expect(bar).not_to_contain_text("官方帐号")
    expect(bar).not_to_contain_text("剪辑任务")
    expect(bar).not_to_contain_text("任务稿件")
    head = page.locator("#pane-editors thead")
    expect(head).to_contain_text("稿件收费方式")
    expect(head).not_to_contain_text("分成比例")
    zhou = page.locator("#edBody tr", has_text="周凯")
    expect(zhou.locator("td").nth(3)).to_contain_text("任务协作 40%")
    expect(zhou.locator("td").nth(3)).to_contain_text("帐号运营 50%")
    expect(zhou.locator("td").nth(4)).to_have_text("跟随平台")
    chen = page.locator("#edBody tr", has_text="陈予")
    expect(chen.locator("td").nth(3)).to_have_text("任务协作 30%")
    expect(chen.locator("td").nth(4)).to_contain_text("定制")
    expect(chen.locator("td").nth(4)).to_contain_text("单次 80 积分")
    su = page.locator("#edBody tr", has_text="苏晚")
    expect(su.locator("td").nth(3)).to_have_text("帐号运营 35%")
    expect(su.locator("td").nth(4)).to_have_text("跟随平台")


def test_editor_detail_and_edit_roundtrip(page, demo_server):
    _admin(page, demo_server)
    page.locator("#edBody tr", has_text="周凯").locator("button", has_text="详情").click()
    detail = page.locator("#detailBody")
    expect(detail.locator("dd").nth(2)).to_have_text("任务协作 40%、帐号运营 50%")
    expect(detail.locator("dd").nth(3)).to_have_text("跟随平台")
    page.locator("#detailClose").click()
    page.locator("#edBody tr", has_text="周凯").locator("button", has_text="编辑").click()
    expect(page.locator("#edModes input[value='任务协作']")).to_be_checked()
    expect(page.locator("#edModes input[value='帐号运营']")).to_be_checked()
    expect(page.locator("#edShareTaskWrap")).to_be_visible()
    expect(page.locator("#edShareAccountWrap")).to_be_visible()
    expect(page.locator("#edShareTask")).to_have_value("40")
    expect(page.locator("#edShareAccount")).to_have_value("50")
    expect(page.locator("#edCharge")).to_have_value("跟随平台")
    expect(page.locator("#edPointsWrap")).to_be_hidden()
    page.locator("#edModes input[value='帐号运营']").uncheck()
    expect(page.locator("#edShareAccountWrap")).to_be_hidden()
    page.locator("#edSave").click()
    row = page.locator("#edBody tr", has_text="周凯")
    expect(row.locator("td").nth(3)).to_have_text("任务协作 40%")
    expect(row.locator("td").nth(4)).to_have_text("跟随平台")


def test_save_blocks_when_no_mode_or_bad_share(page, demo_server):
    _admin(page, demo_server)
    before = page.locator("#edBody tr").count()
    page.locator("#openEditor").click()
    expect(page.locator("#edOverlay")).to_have_class("modal-overlay open")
    expect(page.locator("#edShareTaskWrap")).to_be_hidden()
    expect(page.locator("#edShareAccountWrap")).to_be_hidden()
    expect(page.locator("#edPointsWrap")).to_be_hidden()
    _fill_required(page)
    page.locator("#edSave").click()
    expect(page.locator("#toast")).to_have_text("至少选一个合作模式")
    expect(page.locator("#edOverlay")).to_have_class("modal-overlay open")
    expect(page.locator("#edBody")).not_to_contain_text("YB10999")
    assert page.locator("#edBody tr").count() == before

    page.locator("#edModes input[value='任务协作']").check()
    expect(page.locator("#edShareTaskWrap")).to_be_visible()
    expect(page.locator("#edShareAccountWrap")).to_be_hidden()
    page.locator("#edShareTask").fill("")
    page.locator("#edSave").click()
    expect(page.locator("#toast")).to_have_text("已选模式的分成比例要在 0 到 100")
    expect(page.locator("#edOverlay")).to_have_class("modal-overlay open")

    page.locator("#edShareTask").fill("140")
    page.locator("#edSave").click()
    expect(page.locator("#toast")).to_have_text("已选模式的分成比例要在 0 到 100")
    page.locator("#edShareTask").fill("-1")
    page.locator("#edSave").click()
    expect(page.locator("#toast")).to_have_text("已选模式的分成比例要在 0 到 100")
    expect(page.locator("#edBody")).not_to_contain_text("YB10999")
    page.locator("#edShareTask").fill("0")
    page.locator("#edSave").click()
    saved = page.locator("#edBody tr", has_text="YB10999")
    expect(saved.locator("td").nth(3)).to_have_text("任务协作 0%")
    expect(saved.locator("td").nth(4)).to_have_text("跟随平台")
    page.locator("#openEditor").click()
    page.locator("#edYb").fill("YB10998")
    page.locator("#edName").fill("边界")
    page.locator("#edNote").fill("客服接入")
    page.locator("#edPlatforms input[value='右豹']").check()
    page.locator("#edModes input[value='帐号运营']").check()
    expect(page.locator("#edShareTaskWrap")).to_be_hidden()
    expect(page.locator("#edShareAccountWrap")).to_be_visible()
    page.locator("#edShareAccount").fill("100")
    page.locator("#edSave").click()
    expect(page.locator("#edBody tr", has_text="YB10998").locator("td").nth(3)).to_have_text("帐号运营 100%")


def test_custom_charge_asks_points_and_both_modes_keep_own_ratio(page, demo_server):
    _admin(page, demo_server)
    page.locator("#openEditor").click()
    _fill_required(page)
    page.locator("#edModes input[value='任务协作']").check()
    page.locator("#edModes input[value='帐号运营']").check()
    expect(page.locator("#edShareTaskWrap")).to_be_visible()
    expect(page.locator("#edShareAccountWrap")).to_be_visible()
    page.locator("#edShareTask").fill("40")
    page.locator("#edShareAccount").fill("55")
    page.locator("#edCharge").select_option("定制")
    expect(page.locator("#edPointsWrap")).to_be_visible()
    expect(page.locator("#edPointsWrap")).to_contain_text("单次")
    expect(page.locator("#edPointsWrap")).to_contain_text("积分")
    page.locator("#edSave").click()
    expect(page.locator("#toast")).to_have_text("请填写单次积分")
    expect(page.locator("#edOverlay")).to_have_class("modal-overlay open")
    page.locator("#edPoints").fill("0")
    page.locator("#edSave").click()
    expect(page.locator("#toast")).to_have_text("请填写单次积分")
    page.locator("#edPoints").fill("1.5")
    page.locator("#edSave").click()
    expect(page.locator("#toast")).to_have_text("请填写单次积分")
    page.locator("#edCharge").select_option("跟随平台")
    expect(page.locator("#edPointsWrap")).to_be_hidden()
    page.locator("#edCharge").select_option("定制")
    page.locator("#edPoints").fill("80")
    page.locator("#edSave").click()
    expect(page.locator("#edOverlay")).not_to_have_class("modal-overlay open")
    row = page.locator("#edBody tr", has_text="YB10999")
    expect(row.locator("td").nth(3)).to_contain_text("任务协作 40%")
    expect(row.locator("td").nth(3)).to_contain_text("帐号运营 55%")
    expect(row.locator("td").nth(4)).to_contain_text("定制")
    expect(row.locator("td").nth(4)).to_contain_text("单次 80 积分")
    row.locator("button", has_text="详情").click()
    expect(page.locator("#detailBody")).to_contain_text("定制，单次 80 积分")


def test_fill_count_opens_same_columns(page, demo_server):
    _admin(page, demo_server)
    page.locator("[data-admin='pane-works']").click()
    expect(page.locator("#pane-works")).to_be_visible()
    two = page.locator("#wkBody tr", has_text="掌心宠口播")
    expect(two.locator("[data-fills]")).to_have_text("2")
    two.locator("[data-fills]").click()
    drawer = page.locator("#detailBody")
    expect(page.locator("#detailTitle")).to_have_text("回填作品 · 掌心宠口播")
    for label in ("媒体平台", "帐号ID", "帐号昵称", "作品链接", "发布时间", "回填时间"):
        expect(drawer).to_contain_text(label)
    expect(drawer.locator("tbody tr")).to_have_count(2)
    first = drawer.locator("tbody tr").nth(0)
    expect(first).to_contain_text("抖音")
    expect(first).to_contain_text("dy_zhoukai")
    expect(first).to_contain_text("周凯")
    expect(first).to_contain_text("v.douyin.com/aaa")
    expect(first).to_contain_text("09-26 18:02")
    expect(first).to_contain_text("09-26 18:40")
    expect(drawer.locator("tbody tr").nth(1)).to_contain_text("ks_linxiao")

    page.locator("#detailClose").click()
    zero = page.locator("#wkBody tr", has_text="团宠图集")
    expect(zero.locator("[data-fills]")).to_have_text("0")
    zero.locator("[data-fills]").click()
    expect(page.locator("#detailBody")).to_contain_text("没有回填作品")
    expect(page.locator("#detailBody tbody tr")).to_have_count(0)

    page.locator("#detailClose").click()
    gone = page.locator("#wkBody tr", has_text="退婚口播")
    expect(gone.locator("[data-fills]")).to_have_text("1")
    expect(gone).to_contain_text("已删除")
    expect(gone.locator("[data-fills]")).not_to_contain_text("已删除")
    gone.locator("[data-fills]").click()
    expect(page.locator("#detailBody")).to_contain_text("dy_chenyu")
    expect(page.locator("#detailBody tbody tr")).to_have_count(1)
    expect(page.locator("#detailBody")).not_to_contain_text("已删除")
    expect(page.locator("#detailTitle")).not_to_contain_text("已删除")
    page.locator("#detailClose").click()
    album = page.locator("#wkBody tr", has_text="团宠图集")
    album.locator("button", has_text="删除").click()
    album = page.locator("#wkBody tr", has_text="团宠图集")
    expect(album).to_contain_text("已删除")
    expect(album.locator("[data-fills]")).to_have_text("0")
    expect(album.locator("button", has_text="删除")).to_have_count(0)

    page.locator("[data-wkch='站外']").click()
    expect(page.locator("#wkTitle")).to_have_text("站外稿件")
    head = page.locator("#wkHead")
    expect(head).to_contain_text("状态")
    expect(head).to_contain_text("稿件状态")
    expect(head).to_contain_text("回填作品")
    expect(head).not_to_contain_text("发布技巧")
    expect(head).not_to_contain_text("素材类型")
    expect(head).not_to_contain_text("占用")
    expect(head).not_to_contain_text("审核")
    expect(page.locator("#wkOccField")).to_be_hidden()
    expect(page.locator("#wkAuditField")).to_be_hidden()
    expect(page.locator("#wkOffStField")).to_be_visible()
    expect(page.locator("#wkBody tr", has_text="掌心宠站外文件夹").locator("[data-fills]")).to_have_text("1")
    expect(page.locator("#wkBody tr", has_text="团宠站外夹").locator("[data-fills]")).to_have_text("0")
    off_gone = page.locator("#wkBody tr", has_text="真千金站外夹")
    expect(off_gone).to_contain_text("已删除")
    expect(off_gone.locator("[data-fills]")).to_have_text("1")
    off_gone.locator("[data-fills]").click()
    expect(page.locator("#detailBody")).to_contain_text("ks_suwan")
    expect(page.locator("#detailBody")).not_to_contain_text("已删除")
    page.locator("#detailClose").click()
    page.locator("#wkBody tr", has_text="掌心宠站外文件夹").locator("button", has_text="分享链接").click()
    expect(page.locator("#toast")).to_have_text("已复制")
