"""FR-014 一键代发：feed 隐藏占用、领取门禁、购次、回填、后台页。"""

from playwright.sync_api import expect


def test_feed_hides_occupied_and_claim_requires_keyword(page, demo_server):
    page.goto(f"{demo_server}/yijian-daifa-demo.html", wait_until="domcontentloaded")
    expect(page.locator("#screen-feed")).to_have_class("screen active")
    expect(page.locator("#feedList")).to_contain_text("掌心宠")
    expect(page.locator("#feedList")).not_to_contain_text("团宠解压图集")
    expect(page.locator("#feedList")).not_to_contain_text("银发军官")
    expect(page.locator("#feedList")).not_to_contain_text("待审口播样例")
    expect(page.locator("#feedList")).not_to_contain_text("驳回混剪样例")
    expect(page.locator("#feedList")).not_to_contain_text("¥")
    expect(page.locator("#feedList")).not_to_contain_text("收益")
    expect(page.locator("#plazaBanner")).to_be_visible()
    expect(page.locator("#feedList img.cover-img").first).to_be_visible()
    expect(page.locator("#feedList [data-genre='小说']")).not_to_have_count(0)
    expect(page.locator("#feedList [data-genre='漫画']")).not_to_have_count(0)
    expect(page.locator("#feedList [data-genre='视频']")).not_to_have_count(0)
    expect(page.locator("#feedSearch")).to_be_visible()
    expect(page.locator("#projectRow")).to_be_visible()
    expect(page.locator("#projectRow")).to_contain_text("番茄小说")
    expect(page.locator("#projectRow")).to_contain_text("红果短剧")
    expect(page.locator("#projectRow")).to_contain_text("知乎故事")
    expect(page.locator("#projectRow")).to_contain_text("红果漫剧")
    expect(page.locator("#projectRow .proj-ico img")).to_have_count(4)
    expect(page.locator("#projectRow .proj-ico img").first).to_have_attribute("src", "assets/fr014/logo-fanqie.jpg")

    page.locator(".feed-card").filter(has_text="掌心宠").click()
    expect(page.locator("#screen-detail")).to_have_class("screen active")
    expect(page.locator("#detailBody")).to_contain_text("分成比例")
    expect(page.locator("#detailBody")).to_contain_text("领取步骤")
    expect(page.locator("#detailBody")).to_contain_text("张")
    expect(page.locator("#detailBody")).to_contain_text("书籍 ID")
    expect(page.locator("#detailBody")).to_contain_text("7128491023")
    expect(page.locator("#detailBody .pills")).to_contain_text("甜宠")
    expect(page.locator("#detailNotice")).to_contain_text("24小时内")
    expect(page.locator("#detailNotice")).to_contain_text("终身未回填超过3次")
    expect(page.locator("#detailBody")).not_to_contain_text("¥")
    expect(page.locator("#claimQuotaFoot")).to_contain_text("3")
    page.locator("#quickKw").click()
    expect(page.locator("#toast")).to_contain_text("跳转到对应项目的题词页面")
    page.locator("#goClaim").click()
    expect(page.locator("#kwSheet")).to_have_class("kw-sheet show")
    page.locator("#confirmKw").click()
    expect(page.locator("#toast")).to_contain_text("请先选择该项目已通过的关键关键词")

    page.locator("#kwList .kw-row").first.click()
    page.locator("#confirmKw").click()
    expect(page.locator("#loadText")).to_contain_text("正在下载稿件")
    expect(page.locator("#loadText")).to_contain_text("正在保存到相册")
    expect(page.locator("#loadText")).to_contain_text("已保存到相册")
    expect(page.locator("#toast")).to_contain_text("领取成功")
    expect(page.locator("#screen-detail")).to_have_class("screen active")
    expect(page.locator("#footUnclaimed")).to_be_hidden()
    expect(page.locator("#footClaimed")).to_be_visible()
    expect(page.locator("#detailBody")).to_contain_text("作品发布技巧")
    expect(page.locator("#detailBody")).to_contain_text("发布标题")
    expect(page.locator("#detailBody")).to_contain_text("发布描述")
    expect(page.locator("#detailBody")).not_to_contain_text("领取步骤")
    expect(page.locator("#copyTitle")).to_have_text("添加水印")
    expect(page.locator("#editWork")).to_have_text("下载稿件")
    page.locator("#pubTips [data-copy='title']").click()
    expect(page.locator("#toast")).to_contain_text("已复制发布标题")

    page.locator("#screenNav button", has_text="我的领取").click()
    expect(page.locator("#claimTabs .on")).to_contain_text("未回填")
    expect(page.locator("#claimList")).to_contain_text("掌心宠溺")
    expect(page.locator("#claimList")).to_contain_text("立即回填")
    expect(page.locator("#claimList")).to_contain_text("番茄小说")
    expect(page.locator("#claimList")).to_contain_text("还可下载")
    expect(page.locator("#claimList")).to_contain_text("下载时间")
    expect(page.locator("#claimProjects")).to_contain_text("番茄小说")
    expect(page.locator("#claimProjects")).not_to_contain_text("红果短剧")
    expect(page.locator("#claimProjects")).not_to_contain_text("知乎故事")
    expect(page.locator("#claimProjects")).not_to_contain_text("红果漫剧")
    expect(page.locator("[data-fill]").first).to_have_class("primary")


def test_buy_then_claim_and_fillback(page, demo_server):
    page.goto(f"{demo_server}/yijian-daifa-demo.html?screen=buy", wait_until="domcontentloaded")
    expect(page.locator("#screen-detail")).to_have_class("screen active")
    expect(page.locator("#buySheet")).to_have_class("kw-sheet show")
    expect(page.locator("#skuList .sku")).to_have_count(3)
    page.locator("#skuList .sku").nth(1).click()
    page.locator("#confirmBuy").click()
    expect(page.locator("#toast")).to_contain_text("兑换成功")
    expect(page.locator("#buySheet")).not_to_have_class("kw-sheet show")
    expect(page.locator("#kwSheet")).not_to_have_class("kw-sheet show")
    page.locator("#goClaim").click()
    expect(page.locator("#kwSheet")).to_have_class("kw-sheet show")
    page.locator("#kwList .kw-row").first.click()
    page.locator("#confirmKw").click()
    expect(page.locator("#toast")).to_contain_text("领取成功")
    expect(page.locator("#copyTitle")).to_have_text("添加水印")
    expect(page.locator("#editWork")).to_have_text("下载稿件")
    page.locator("#screenNav button", has_text="我的领取").click()
    page.locator("[data-fill]").first.click()
    expect(page.locator("#screen-fillback")).to_have_class("screen active")
    page.locator("#doFill").click()
    expect(page.locator("#toast")).to_contain_text("回填完成")
    expect(page.locator("#claimTabs .on")).to_contain_text("已回填")
    expect(page.locator("#claimList")).to_contain_text("掌心宠溺")
    expect(page.locator("[data-fill]").first).to_have_class("primary")
    page.locator("#screenNav button", has_text="作品广场").click()
    expect(page.locator("#feedList")).not_to_contain_text("掌心宠")
    page.locator("#screenNav button", has_text="我的领取").click()
    page.locator("[data-fill]").first.click()
    expect(page.locator("#toast")).to_contain_text("该稿件已回填")


def test_timeout_and_banned_scenes(page, demo_server):
    page.goto(f"{demo_server}/yijian-daifa-demo.html?screen=timeout", wait_until="domcontentloaded")
    expect(page.locator("#claimTabs .on")).to_contain_text("已超时")
    expect(page.locator("#claimList")).to_contain_text("掌心宠溺")
    expect(page.locator("#claimList")).to_contain_text("下载已过期")
    page.locator("[data-dl]").first.click()
    expect(page.locator("#toast")).to_contain_text("领取已超过 7 天，无法再下载")
    page.locator("[data-fill]").first.click()
    expect(page.locator("#toast")).to_contain_text("已超时，无法回填")
    page.goto(f"{demo_server}/yijian-daifa-demo.html?screen=banned", wait_until="domcontentloaded")
    expect(page.locator("#goClaim")).to_have_text("已被停权，无法领取")


def test_fr_shell_admin_and_flow(page, demo_server):
    page.goto(f"{demo_server}/fr-opc-yijian-daifa.html", wait_until="domcontentloaded")
    expect(page.locator("h1")).to_contain_text("一键代发")
    expect(page.locator("#feDemo h2")).to_contain_text("前端交互 Demo")
    expect(page.locator("#feScenes")).to_contain_text("作品广场")
    expect(page.locator("#feScenes")).to_contain_text("招募海报")
    expect(page.locator("#feScenes")).to_contain_text("浮层兑换")
    expect(page.locator('[data-preview="fe"]')).to_have_text("全屏预览")
    expect(page.locator("#mockupFrame")).to_be_visible()
    page.evaluate(
        """() => {
          HTMLElement.prototype.requestFullscreen = function () {
            return Promise.reject(new Error('no-fs'));
          };
        }"""
    )
    page.locator('[data-preview="fe"]').click()
    expect(page.locator("body")).to_have_class("preview-fs-fallback")
    expect(page.locator("#feDemo")).to_have_class("demo-layout is-preview")
    expect(page.locator('[data-preview="fe"]')).to_have_text("退出全屏")
    page.locator('[data-preview="fe"]').click()
    expect(page.locator("body")).not_to_have_class("preview-fs-fallback")
    expect(page.locator('[data-preview="fe"]')).to_have_text("全屏预览")
    page.locator('.page-tab-bar button[data-page="view-admin"]').click()
    expect(page.locator("#admin-editors")).to_be_visible()
    expect(page.locator("#edBody")).to_contain_text("林夏")
    page.locator('.admin-tab-bar button[data-admin="admin-skus"]').click()
    expect(page.locator("#skuBody")).to_contain_text("120")
    page.locator('.page-tab-bar button[data-page="view-flow"]').click()
    expect(page.locator(".flow-svg-wrap")).to_contain_text("已选通过关键词?")
    expect(page.locator(".flow-svg-wrap")).to_contain_text("稿件空闲未占用?")
    expect(page.locator(".flow-svg-wrap")).to_contain_text("项目已启用?")
    expect(page.locator(".flow-svg-wrap")).to_contain_text("审核通过?")
    expect(page.locator(".flow-svg-wrap")).to_contain_text("后台手动恢复")
    page.locator("#toggleRuleDrawer").click()
    expect(page.locator("#ruleDrawer")).to_have_class("drawer open")
    expect(page.locator("#rule-fe")).to_contain_text("作品广场")
    expect(page.locator(".badge-version")).to_contain_text("v6")
    page.locator("#ruleDrawer .drawer-close").click()
    expect(page.locator("#ruleDrawer")).not_to_have_class("drawer open")
    page.locator('.page-tab-bar button[data-page="view-pc"]').click()
    expect(page.locator("#pcDemo h2")).to_contain_text("PC端 Demo")
    expect(page.locator("#pcFrame")).to_be_visible()
    expect(page.locator("#pcScenes")).to_contain_text("剪辑供稿")
    expect(page.locator('[data-preview="pc"]')).to_have_text("全屏预览")


def test_covers_banner_poster_and_claim_detail(page, demo_server):
    page.goto(f"{demo_server}/yijian-daifa-demo.html", wait_until="domcontentloaded")
    expect(page.locator("#feedList .art")).to_have_count(0)
    expect(page.locator("#feedList img.cover-img").first).to_have_attribute("src", "assets/fr014/cover-m01.jpg")
    expect(page.locator("#plazaBanner .bn-slide")).to_have_count(5)
    expect(page.locator("#plazaBanner .bn-dot")).to_have_count(5)
    first_bn = page.locator("#plazaBanner .bn-slide.on").get_attribute("data-bn")
    page.wait_for_function(
        """(prev) => {
          const on = document.querySelector('#plazaBanner .bn-slide.on');
          return on && on.getAttribute('data-bn') !== prev;
        }""",
        arg=first_bn,
        timeout=8000,
    )
    page.locator("#plazaBanner .bn-dot").nth(2).click()
    expect(page.locator("#plazaBanner .bn-slide").nth(2)).to_have_class("bn-slide on")
    expect(page.locator("#plazaBanner .bn-dot").nth(2)).to_have_class("bn-dot on")
    page.locator("#plazaBanner .bn-dot").nth(0).click()
    expect(page.locator("#plazaBanner .bn-slide").nth(0)).to_have_class("bn-slide on")
    page.locator("#plazaBanner .bn-slide.on").click()
    expect(page.locator("#screen-poster")).to_have_class("screen active")
    expect(page.locator("#screen-poster")).to_contain_text("卖点")
    expect(page.locator("#screen-poster")).to_contain_text("适合谁")
    expect(page.locator("#screen-poster .qr")).to_be_visible()
    expect(page.locator("#screen-poster form")).to_have_count(0)
    expect(page.locator("#screen-editor-upload")).to_have_count(0)
    page.locator("#screen-poster .back").click()
    expect(page.locator("#screen-feed")).to_have_class("screen active")

    page.evaluate(
        """() => {
          BANNERS.forEach(function (b) { b.on = b.id === 'B-02'; });
          renderPlazaBanner();
        }"""
    )
    page.locator("#screenNav button", has_text="作品广场").click()
    expect(page.locator("#plazaBanner .bn-slide")).to_have_count(1)
    expect(page.locator("#plazaBanner .bn-dot")).to_have_count(0)
    page.evaluate(
        """() => {
          BANNERS.forEach(function (b) { b.on = false; });
          renderPlazaBanner();
        }"""
    )
    expect(page.locator("#plazaBanner")).to_be_hidden()

    page.goto(f"{demo_server}/yijian-daifa-demo.html?screen=claims", wait_until="domcontentloaded")
    page.locator("#claimTabs button", has_text="已回填").click()
    expect(page.locator("#claimList img.cover-img").first).to_be_visible()
    expect(page.locator("#claimList")).to_contain_text("番茄小说")
    expect(page.locator("#claimList")).to_contain_text("下载时间")
    expect(page.locator("#claimList")).to_contain_text("还可下载")
    expect(page.locator("[data-fill]").first).to_have_class("primary")
    page.locator("[data-fill]").first.click()
    expect(page.locator("#toast")).to_contain_text("该稿件已回填")
    page.locator("#claimList .c-hit").first.click()
    expect(page.locator("#screen-detail")).to_have_class("screen active")
    expect(page.locator("#detailBody img.cover-img")).to_be_visible()
    expect(page.locator("#detailBody .art")).to_have_count(0)
    expect(page.locator("#copyTitle")).to_have_text("添加水印")
    expect(page.locator("#editWork")).to_have_text("下载稿件")
    expect(page.locator("#footClaimed")).not_to_have_class("hidden")
    expect(page.locator("#detailBody")).to_contain_text("作品发布技巧")
    expect(page.locator("#detailBody")).to_contain_text("银发军官把我宠上天｜年代图集")
    expect(page.locator("#detailBody")).to_contain_text("书籍 ID")
    expect(page.locator("#detailBody")).to_contain_text("7482019356")
    expect(page.locator("#detailBody .pills")).to_contain_text("年代")
    expect(page.locator("#detailNotice")).to_be_visible()
    page.locator("#pubTips [data-copy='desc']").click()
    expect(page.locator("#toast")).to_contain_text("已复制发布描述")
    page.locator("#copyTitle").click()
    expect(page.locator("#screen-watermark")).to_have_class("screen active")
    expect(page.locator("#wmMark")).to_contain_text("年代甜宠")
    expect(page.locator("#wmTabs")).to_contain_text("字体")
    expect(page.locator("#wmTabs")).to_contain_text("水印")
    expect(page.locator("#wmFonts")).to_contain_text("思源黑体")
    expect(page.locator("#wmFonts")).to_contain_text("站酷快乐体")
    h0 = page.locator("#wmPanes").bounding_box()["height"]
    page.locator("#wmTabs button", has_text="字色").click()
    expect(page.locator("#wmColorA")).to_be_visible()
    h1 = page.locator("#wmPanes").bounding_box()["height"]
    page.locator("#wmTabs button", has_text="水印").click()
    h2 = page.locator("#wmPanes").bounding_box()["height"]
    assert abs(h0 - h1) < 2 and abs(h1 - h2) < 2
    expect(page.locator("#wmModes")).to_contain_text("每2张打10张水印")
    page.locator("#wmText").click()
    expect(page.locator("#wmText")).to_be_focused()
    expect(page.locator("#wmText")).to_be_in_viewport()
    expect(page.locator("#wmTabs")).to_be_in_viewport()
    expect(page.locator("#dlWm")).to_be_in_viewport()
    page.locator("#dlWm").click()
    expect(page.locator("#loadText")).to_contain_text("正在打水印")
    expect(page.locator("#loadText")).to_contain_text("正在下载")
    expect(page.locator("#loadSub")).to_contain_text("张")
    expect(page.locator("#toast")).to_contain_text("水印稿件已保存到相册")
    page.locator("#screen-watermark .back").click()
    expect(page.locator("#screen-detail")).to_have_class("screen active")
    page.locator("#editWork").click()
    expect(page.locator("#loadText")).to_contain_text("正在下载")
    expect(page.locator("#loadSub")).to_contain_text("张")
    expect(page.locator("#toast")).to_contain_text("稿件已保存到相册")
    page.locator("#screen-detail .back").click()
    expect(page.locator("#screen-claims")).to_have_class("screen active")

    page.goto(f"{demo_server}/yijian-daifa-demo.html?screen=fillback", wait_until="domcontentloaded")
    expect(page.locator("#screen-fillback")).to_have_class("screen active")
    page.locator("#screenNav button", has_text="我的领取").click()
    expect(page.locator("#claimTabs .on")).to_contain_text("未回填")
    page.locator("[data-fill]").first.click()
    expect(page.locator("#screen-fillback")).to_have_class("screen active")


def test_admin_editors_works_projects(page, demo_server):
    page.goto(f"{demo_server}/fr-opc-yijian-daifa.html?tab=admin", wait_until="domcontentloaded")
    expect(page.locator('.admin-tab-bar button[data-admin="admin-banners"]')).to_have_count(0)
    expect(page.locator("#edBody")).to_contain_text("YB10086")
    expect(page.locator("#edBody")).to_contain_text("50%")
    expect(page.locator("#edBody")).to_contain_text("主力口播")
    page.locator("#admin-editors button", has_text="录入").click()
    expect(page.locator("#appModal")).to_contain_text("右豹 ID")
    expect(page.locator("#appModal")).to_contain_text("分成比例")
    expect(page.locator("#appModal")).to_contain_text("备注")
    page.locator("#modalOk").click()
    expect(page.locator("#toast")).to_contain_text("请填写右豹 ID、分成比例、备注")
    page.locator("#mYb").fill("YB19999")
    page.locator("#mName").fill("新剪辑")
    page.locator("#mShare").fill("45%")
    page.locator("#mNote").fill("客服新录入")
    page.locator("#modalOk").click()
    expect(page.locator("#edBody")).to_contain_text("YB19999")

    page.locator('.admin-tab-bar button[data-admin="admin-works"]').click()
    expect(page.locator("#wkBody")).to_contain_text("番茄小说")
    expect(page.locator("#wkBody")).to_contain_text("书籍 ID 7128491023")
    expect(page.locator("#wkBody")).to_contain_text("18.6 MB")
    expect(page.locator("#wkBody")).to_contain_text("https://ybdd.demo/ms/M-01")
    expect(page.locator("#wkBody")).to_contain_text("被偏爱的感觉藏不住｜掌心宠口播")
    page.locator("#wkBody button", has_text="详情").first.click()
    expect(page.locator("#detailDrawer")).to_have_class("drawer open")
    expect(page.locator("#detailBody")).to_contain_text("书籍 ID")
    expect(page.locator("#detailBody")).to_contain_text("文件大小")
    expect(page.locator("#detailBody")).to_contain_text("作品标题")
    page.locator("#detailDrawer .drawer-close").click()

    page.locator('.admin-tab-bar button[data-admin="admin-projects"]').click()
    expect(page.locator("#pjBody")).to_contain_text("番茄小说")
    expect(page.locator("#pjBody")).to_contain_text("启用")
    page.locator("#admin-projects button", has_text="添加").click()
    page.locator("#pjName").fill("测试项目")
    page.locator("#pjSort").fill("9")
    page.locator("#modalOk").click()
    expect(page.locator("#pjBody")).to_contain_text("测试项目")
    page.locator("#pjBody button", has_text="编辑").first.click()
    expect(page.locator("#appModal")).to_contain_text("项目名称")
    expect(page.locator("#appModal")).to_contain_text("Logo 信息")
    page.locator("#pjOn").select_option("禁用")
    page.locator("#modalOk").click()
    expect(page.locator("#pjBody")).to_contain_text("禁用")

    page.locator('.admin-tab-bar button[data-admin="admin-claims"]').click()
    page.locator("#clBody button", has_text="稿件详情").first.click()
    expect(page.locator("#detailDrawer")).to_have_class("drawer open")
    expect(page.locator("#detailTitle")).to_contain_text("稿件详情")
    expect(page.locator("#detailBody")).to_contain_text("银发军官")
    expect(page.locator("#detailBody")).to_contain_text("番茄小说")
    page.locator("#detailDrawer .drawer-close").click()
    page.locator("#clBody button", has_text="详情").first.click()
    expect(page.locator("#detailBody")).to_contain_text("回填")


def test_watermark_video_progress(page, demo_server):
    page.goto(f"{demo_server}/yijian-daifa-demo.html", wait_until="domcontentloaded")
    page.evaluate(
        """() => {
          var it = item('M-02');
          it.occupied = true;
          state.claims.unshift(makeClaim(it, { id: 'C-v', kw: '末世囤货', status: '未回填' }));
          state.current = 'M-02';
        }"""
    )
    page.locator("#screenNav button", has_text="添加水印").click()
    expect(page.locator("#screen-watermark")).to_have_class("screen active")
    page.locator(".phone-frame").scroll_into_view_if_needed()
    expect(page.locator("#wmMark")).to_contain_text("末世囤货")
    expect(page.locator("#dlWm")).to_be_in_viewport()
    expect(page.locator("#wmText")).to_be_in_viewport()
    page.locator("#wmTabs button", has_text="字色").click()
    expect(page.locator("#wmColors .wm-sw")).to_have_count(10)
    page.locator("#wmTabs button", has_text="背景").click()
    expect(page.locator("#wmBgs .wm-sw")).to_have_count(11)
    page.locator("#dlWm").click()
    expect(page.locator("#loadText")).to_contain_text("正在打水印")
    expect(page.locator("#loadBarWrap")).to_have_class("load-bar show")
    expect(page.locator("#loadSub")).to_contain_text("%")
    expect(page.locator("#toast")).to_contain_text("水印稿件已保存到相册")


def test_pc_recruit_board_and_upload_list(page, demo_server):
    page.goto(f"{demo_server}/yijian-daifa-pc.html?screen=home", wait_until="domcontentloaded")
    expect(page.locator("#recruitBn")).to_be_visible()
    expect(page.locator("#stAuth")).to_contain_text("2")
    expect(page.locator("#stUp")).to_contain_text("2")
    expect(page.locator("#stClaim")).to_contain_text("1")
    expect(page.locator("#stEarn")).to_contain_text("186")
    expect(page.locator("#authChips")).to_contain_text("番茄小说")
    expect(page.locator("#authChips")).to_contain_text("红果漫剧")
    expect(page.locator("#boardEmpty")).to_be_hidden()
    expect(page.locator("#recentBox")).to_contain_text("6641029385")
    expect(page.locator("#recentBox")).to_contain_text("21.8 MB")
    expect(page.locator("#recentBox")).to_contain_text("走入没有你的夜")

    page.locator("#recruitBn").click()
    expect(page.locator("#recruitDrawer")).to_have_class("drawer open")
    expect(page.locator("#recruitDrawer")).to_contain_text("卖点")
    expect(page.locator("#recruitDrawer")).to_contain_text("适合谁")
    expect(page.locator("#recruitDrawer .qr")).to_be_visible()
    expect(page.locator("#recruitDrawer input")).to_have_count(0)
    expect(page.locator("#recruitDrawer form")).to_have_count(0)
    page.locator("#recruitClose").click()
    expect(page.locator("#recruitDrawer")).not_to_have_class("drawer open")

    page.goto(f"{demo_server}/yijian-daifa-pc.html?screen=guest", wait_until="domcontentloaded")
    expect(page.locator("#recruitBn")).to_be_visible()
    expect(page.locator("#boardEmpty")).to_be_visible()
    expect(page.locator("#boardEmpty")).to_contain_text("还不是剪辑手")
    expect(page.locator("#boardReady")).to_be_hidden()
    expect(page.locator("#goUpload")).to_be_hidden()

    page.goto(f"{demo_server}/yijian-daifa-pc.html?screen=list", wait_until="domcontentloaded")
    expect(page.locator("#listBox")).to_contain_text("书籍 ID")
    expect(page.locator("#listBox")).to_contain_text("已通过")
    expect(page.locator("#listBox")).not_to_contain_text("ybdd.demo/ms")
    expect(page.locator("#listBox tr", has_text="银发军官图集").locator("button", has_text="删除")).to_be_disabled()


def test_admin_fe_store_loop(page, demo_server):
    page.goto(f"{demo_server}/fr-opc-yijian-daifa.html?tab=admin", wait_until="domcontentloaded")
    page.locator('.admin-tab-bar button[data-admin="admin-projects"]').click()
    page.locator("#pjBody tr", has_text="知乎故事").locator("button", has_text="编辑").click()
    page.locator("#pjOn").select_option("禁用")
    page.locator("#modalOk").click()
    expect(page.locator("#toast")).to_contain_text("已更新项目")

    page.goto(f"{demo_server}/yijian-daifa-demo.html?embed=1", wait_until="domcontentloaded")
    expect(page.locator("#projectRow")).to_contain_text("番茄小说")
    expect(page.locator("#projectRow")).not_to_contain_text("知乎故事")
    expect(page.locator("#feedList")).not_to_contain_text("百日新娘")

    page.goto(f"{demo_server}/fr-opc-yijian-daifa.html?tab=admin", wait_until="domcontentloaded")
    page.locator('.admin-tab-bar button[data-admin="admin-projects"]').click()
    page.locator("#pjBody tr", has_text="番茄小说").locator("button", has_text="编辑").click()
    page.locator("#pjOn").select_option("禁用")
    page.locator("#modalOk").click()
    page.goto(f"{demo_server}/yijian-daifa-demo.html?embed=1&screen=detail", wait_until="domcontentloaded")
    expect(page.locator("#goClaim")).to_have_text("当前不可领")
    expect(page.locator("#goClaim")).to_be_disabled()

    page.goto(f"{demo_server}/fr-opc-yijian-daifa.html?tab=admin", wait_until="domcontentloaded")
    page.locator('.admin-tab-bar button[data-admin="admin-projects"]').click()
    page.locator("#pjBody tr", has_text="番茄小说").locator("button", has_text="编辑").click()
    page.locator("#pjOn").select_option("启用")
    page.locator("#modalOk").click()

    page.goto(f"{demo_server}/yijian-daifa-pc.html?embed=1&screen=upload", wait_until="domcontentloaded")
    expect(page.locator("#upModal")).to_have_class("up-modal open")
    page.locator("#upUseDemo").click()
    page.locator("#upNext").click()
    page.locator("#upTitleField").fill("闭环测试书")
    page.locator("#upBook").fill("闭环测试书")
    page.locator("#upBookId").fill("B-LOOP")
    page.locator("#upFileName").fill("闭环测试书")
    page.locator("#upPubT").fill("闭环测试书")
    page.locator("#upPubD").fill("闭环测试描述")
    page.locator("#upNext").click()
    page.locator("#doPublish").click()
    expect(page.locator("#toast")).to_contain_text("已提交审核")
    expect(page.locator("#listBox")).to_contain_text("闭环测试书")
    expect(page.locator("#listBox")).to_contain_text("审核中")
    expect(page.locator("#listBox")).to_contain_text("B-LOOP")
    expect(page.locator("#listBox")).not_to_contain_text("ybdd.demo/ms")

    page.goto(f"{demo_server}/yijian-daifa-demo.html?embed=1", wait_until="domcontentloaded")
    expect(page.locator("#feedList")).not_to_contain_text("闭环测试书")

    page.goto(f"{demo_server}/fr-opc-yijian-daifa.html?tab=admin", wait_until="domcontentloaded")
    page.locator('.admin-tab-bar button[data-admin="admin-works"]').click()
    expect(page.locator("#wkBody")).to_contain_text("闭环测试书")
    expect(page.locator("#wkBody")).to_contain_text("审核中")
    page.locator("#wkBody tr", has_text="闭环测试书").locator("button", has_text="通过").click()
    expect(page.locator("#toast")).to_contain_text("已通过")

    page.goto(f"{demo_server}/yijian-daifa-demo.html?embed=1", wait_until="domcontentloaded")
    expect(page.locator("#feedList")).to_contain_text("闭环测试书")
    expect(page.locator("#feedList")).not_to_contain_text("待审口播样例")
    expect(page.locator("#feedList")).not_to_contain_text("驳回混剪样例")

    page.goto(f"{demo_server}/fr-opc-yijian-daifa.html?tab=admin", wait_until="domcontentloaded")
    page.locator('.admin-tab-bar button[data-admin="admin-works"]').click()
    page.locator("#wkBody tr", has_text="待审口播样例").locator("button", has_text="驳回").click()
    page.locator("#modalOk").click()
    expect(page.locator("#toast")).to_contain_text("请填写驳回原因")
    page.locator("#rjReason").fill("封面缺失")
    page.locator("#modalOk").click()
    expect(page.locator("#toast")).to_contain_text("已驳回")
    expect(page.locator("#wkBody tr", has_text="待审口播样例")).to_contain_text("封面缺失")
    expect(page.locator("#wkBody tr", has_text="闭环测试书").locator("button", has_text="驳回")).to_have_count(0)

    page.goto(f"{demo_server}/yijian-daifa-demo.html?embed=1", wait_until="domcontentloaded")
    expect(page.locator("#feedList")).not_to_contain_text("待审口播样例")

    page.goto(f"{demo_server}/fr-opc-yijian-daifa.html?tab=admin", wait_until="domcontentloaded")
    page.locator('.admin-tab-bar button[data-admin="admin-projects"]').click()
    page.locator("#pjBody tr", has_text="番茄小说").locator("button", has_text="编辑").click()
    page.locator("#pjOn").select_option("禁用")
    page.locator("#modalOk").click()
    page.goto(f"{demo_server}/yijian-daifa-pc.html?embed=1&screen=upload", wait_until="domcontentloaded")
    page.locator("#upUseDemo").click()
    page.locator("#upNext").click()
    expect(page.locator("#upProject")).not_to_contain_text("番茄小说")
    expect(page.locator("#upProject")).to_contain_text("红果漫剧")

    page.goto(f"{demo_server}/fr-opc-yijian-daifa.html?tab=admin", wait_until="domcontentloaded")
    page.locator('.admin-tab-bar button[data-admin="admin-projects"]').click()
    page.locator("#pjBody tr", has_text="番茄小说").locator("button", has_text="编辑").click()
    page.locator("#pjOn").select_option("启用")
    page.locator("#modalOk").click()

    page.goto(f"{demo_server}/yijian-daifa-pc.html?embed=1&screen=list", wait_until="domcontentloaded")
    page.locator("#listBox tr", has_text="闭环测试书").locator("button", has_text="删除").click()
    page.locator("#pcConfirmOk").click()
    expect(page.locator("#toast")).to_contain_text("已删除")
    expect(page.locator("#listBox")).not_to_contain_text("闭环测试书")
